### PR TITLE
refactor(config): remove `polaris.toml` to simplify infra for brick 

### PR DESCRIPTION
**Pull request by itsdevbear**

### CODE REVIEW

**Comment by itsdevbear** [comment]
@calbera @BrickBera should be ready 

@BrickBera you'll need to modify your infra

**Review by calbera — APPROVED** [review]
lgtm, will update bera to this as soon as in

**Comment by itsdevbear** [comment]
just wrangling tests

**Comment by itsdevbear** [comment]
@Mergifyio refresh

**Pull request merged**
