### PR TITLE
perf(handler): add retry logic to broadcasting to cometbft mempool

### PR DESCRIPTION
**Pull request by itsdevbear**
### Summary by CodeRabbit

- New Feature: Introduced a retry mechanism for failed transactions, enhancing the reliability of transaction broadcasting. This feature automatically attempts to re-broadcast any transactions that initially fail, improving the overall user experience by ensuring transactions are processed more consistently.
- Test: Enhanced JSON RPC test handling with additional assertions for nonce values and a new helper function. This ensures more robust testing and validation of transactions, contributing to the overall stability and reliability of the system.
- Refactor: Improved code structure and clarity by renaming and modifying key functions, making the system easier to maintain and update in the future.

### CODE REVIEW

**Comment by itsdevbear** [comment]
might upgrade this to use a heap + exponential backoff.

**Comment by calbera** [comment]
makes sense so far. can also get more sophisticated with retry priority

**Comment by itsdevbear** [comment]
yup, was a 2am first pass for sure.

**Comment by itsdevbear** [comment]
in practice, the retries will almost never be useful. If the retries are even required something has likely gone really wrong with comet.

**Comment by itsdevbear** [comment]
I am still pro gossip via geth devp2p

**Comment by calbera** [comment]
yeah broadly agree, seems like overall more performant/battle-tested

**Review by ocnc — APPROVED** [review]

**Pull request merged**
