### PR TITLE
refactor(plugin): stateless gas plugin implementation

### PR DESCRIPTION
**Pull request by oofncubed**

### CODE REVIEW

**Comment by itsdevbear** [comment]
Is this good?

**Comment by oofncubed** [comment]
> Is this good?

tests pass and mage start still good

**Comment by itsdevbear** [comment]
Can you add a few more tests around consumption and edge cases

**Comment by itsdevbear** [comment]
I think we actually shelf this for now. It feels a little cosmos specific and I don't wanna break stuff kek

**Pull request closed without merging**
