### PR TITLE
fix(mempool): Fix mempool iteration pattern for pending txs

### PR DESCRIPTION
**Pull request by calbera**

### CODE REVIEW

**Comment by itsdevbear** [comment]
@calbera reach my desk when u have a min to chat bout dis

**Review by itsdevbear — APPROVED** [review]

**Comment by itsdevbear** [comment]
makes sense

**Comment by itsdevbear** [comment]
looks like this is not logically equivalent

**Comment by calbera** [comment]
its logically more correct than before. theres only 2 exact cases in which the next seen tx is pending

**Comment by itsdevbear** [comment]
ye meant it more like tests are gonna fail haha

**Comment by calbera** [comment]
closing in favor of #1039

**Pull request closed without merging**
