### PR TITLE
chore(go): `go 1.21`

### PR DESCRIPTION
**Pull request by itsdevbear**

### CODE REVIEW

**Comment by itsdevbear** [comment]
codecov not updated yet apparently.

**Comment by calbera** [comment]
Seems like the docker e2e tests are not happy, may need to update the dockerfiles?

**Comment by itsdevbear** [comment]
@archbear nice fix, seems like we gotta wait for codeql tho: https://github.com/github/roadmap/issues/806

**Review by calbera — APPROVED** [review]

**Comment by calbera** [comment]
merge conflict

**Comment by calbera** [comment]
does this fix the e2e tests? they've become unstable in the past week

**Comment by itsdevbear** [comment]
replaced by #999

**Pull request closed without merging**
