### PR TITLE
Revert "chore(deps): bump github.com/gin-gonic/gin from 1.9.0 to 1.9.…

### PR DESCRIPTION
**Pull request by calbera**
…1 in /cosmos (#778)"

This reverts commit 4dcc570c4eba89b192e02ff6cd2191f5aa146225.

### CODE REVIEW

**Comment by itsdevbear** [comment]
sorry for accident tags lol

**Comment by smsunarto** [comment]
lgtm ship it gg no re

**Comment by yihuang** [comment]
do you meet issues with gin 1.9.1?

**Comment by itsdevbear** [comment]
turned out to be a `go work sync` issue, go workspaces can be funky sometimes

**Pull request merged**
