### PR TITLE
fix(x/evm): get EVMDenom from store instead of hardcode to "abera"

### PR DESCRIPTION
**Pull request by BrickBera**
tested with "mage start"

### CODE REVIEW

**Comment by calbera** [comment]
looks great!

**Comment by itsdevbear** [comment]
utACK 🎉

**Review by itsdevbear — APPROVED** [review]

**Comment by calbera** [comment]
can we also remove `"abera"` from other places in the code?

**Comment by BrickBera** [comment]
> can we also remove `"abera"` from other places in the code?

Other places in cosmos/x:
1. https://github.com/berachain/polaris/blob/main/cosmos/x/evm/types/params.go#L32
This is for DefaultParams, should be ok?
2. https://github.com/berachain/polaris/blob/main/cosmos/x/evm/plugins/state/plugin_test.go#L496
This is a test, should be good

**Comment by itsdevbear** [comment]
> 

yeah I think these two are fine. The only thing we could do is abstract it into a variable but I think its not that srs atm

**Comment by itsdevbear** [comment]
gj @BrickBera 🎉

**Pull request merged**
