### PR TITLE
chore: Fix Module Accounts for Precompile Contracts

### PR DESCRIPTION
**Pull request by calbera**

### CODE REVIEW

**Review by itsdevbear — APPROVED** [review]
lgtm, but remove println's and fix linter.

**Comment by itsdevbear** [comment]
oh add the checks to the creation of the keepers similar to: https://github.com/cosmos/cosmos-sdk/blob/4f00acfc24902677c56bf49d3f3b58f10de10471/x/staking/keeper/keeper.go#L41

**Comment by calbera** [comment]
```
6:59PM ERR failure when running app err="failed to get address from Keyring: staking.info: key not found [cosmos/cosmos-sdk@v0.46.0-beta2.0.20230423204932-f0018246f107/crypto/keyring/keyring.go:514]"
Error: running "./cosmos/runtime/localnode/init.sh " failed with exit code 1
```

**Comment by calbera** [comment]
init.sh changes
```
PRECOMPILES[0]="staking" # "polar1mx5e3jkxvzf8frl7cl8m69264ctn0shlz6zxjx" # staking
PRECOMPILES[1]="bank" # "polar1gwqac243g2z3vryqsev6acq965f9ttwhjgk226" # bank
PRECOMPILES[2]="gov" # "polar10d07y265gmmuvt4z0w9aw880jnsr700j33u8zp" # governance
PRECOMPILES[3]="auth" # "polar1hh6fc0pcsggzlsqhl7mxzyyvvw5rd5r9vff2ea" # auth
PRECOMPILES[4]="distribution" # "polar1jv65s3grqf6v6jl3dp4t6c9t9rk99cd8vvt7ad" # distribution
PRECOMPILES[5]="erc20" # "polar1glht96kr2rseywuvhhay894qw7ekuc4qphuca5" # erc20

	## Fund all precompile addresses with 1abera (https://ethereum.stackexchange.com/questions/68056/puppeth-precompile-addresses)
	for PRECOMPILE in "${PRECOMPILES[@]}"; do
		./bin/polard genesis add-genesis-account $PRECOMPILE 1abera --keyring-backend $KEYRING --home "$HOMEDIR" --module-name $PRECOMPILE
	done
```

**Pull request closed without merging**
